---
- hosts: linux
  gather_facts: yes

- import_playbook: ubuntu/setup.yml
  when: ansible_os_family == 'Debian'

- import_playbook: fedora/setup.yml
  when: ansible_os_family == 'RedHat'

- import_playbook: common/setup.yml
