---
- name: Main setup
  hosts: linux
  gather_facts: true

- name: Import Ubuntu Setup tasks
  import_playbook: ubuntu/setup.yml
  when: ansible_os_family == 'Debian'

- name: Import Fedora Setup tasks
  import_playbook: fedora/setup.yml
  when: ansible_os_family == 'RedHat'

- name: Import Commmon Setup tasks
  import_playbook: common/setup.yml
