---
tmux:
  files:
    - filename: ".tmux.conf"
      url: https://raw.githubusercontent.com/gpakosz/.tmux/master/.tmux.conf
    - filename: ".tmux.local.conf"
      url: https://raw.githubusercontent.com/gpakosz/.tmux/master/.tmux.conf.local
  config:
    - regexp: "^tmux_conf_new_pane_reconnect_ssh=false"
      line: "tmux_conf_new_pane_reconnect_ssh=true"
    - regexp: "^tmux_conf_24b_colour=false"
      line: "tmux_conf_24b_colour=true"
    - regexp: "^tmux_conf_theme_highlight_focused_pane=false"
      line: "tmux_conf_theme_highlight_focused_pane=true"
    - regexp: "^tmux_conf_copy_to_os_clipboard=false"
      line: "tmux_conf_copy_to_os_clipboard=true"
    - regexp: "^(tmux_conf_theme_(left|right)_separator_.*)=\"(.*)\"$"
      line: '#\1="\3"'
  theme_block: |
    tmux_conf_theme_left_separator_main="\uE0B0"  # /!\ you don't need to install Powerline
    tmux_conf_theme_left_separator_sub="\uE0B1"   #   you only need fonts patched with
    tmux_conf_theme_right_separator_main="\uE0B2" #   Powerline symbols or the standalone
    tmux_conf_theme_right_separator_sub="\uE0B3"  #   PowerlineSymbols.otf font, see README.md
