---
zsh:
  znap:
    path: /usr/share/znap
    url: https://github.com/marlonrichert/zsh-snap.git
    repos_dir: ~/.config/znap

  # plugins:
  #   - 3v1n0/zsh-bash-completions-fallback
  #   - chitoku-k/fzf-zsh-completions
  #   - eastokes/aws-plugin-zsh
  #   - zsh-users/zsh-autosuggestions
  #   - zsh-users/zsh-history-substring-search

  oh_my_zsh_plugins:
    - ansible
    - aws
    - colorize
    - common-aliases
    - docker
    - docker-compose
    - encode64
    - git
    - git-extras
    - git-lfs
    - github
    - gitignore
    - golang
    - gradle
    - lib/clipboard
    - tig
    - tmux
    - tmuxinator
    - zsh-interactive-cd

  plugins:
    - CristianCantoro/colorbira-zsh-theme
    - marlonrichert/zsh-autocomplete
    - marlonrichert/zsh-edit
    - chrissicool/zsh-256color
    - unixorn/git-extra-commands
    - peterhurford/git-aliases.zsh
    - jonmosco/kube-ps1
    - tjquillan/zsh-pipenv
    - mattberther/zsh-pyenv

  theme: colorbira-zsh-theme
