---
- name: Initialize variables
  ansible.builtin.include_vars: vars/graphical.yml

- name: Install GNOME packages
  ansible.builtin.apt:
    name: "{{ gnome_pkgs }}"
    state: present
  when: desktop == "gnome"

- name: Install Nautilus image helpers
  ansible.builtin.apt:
    name: "{{ image_pkgs }}"
    state: present
  when: desktop == "gnome"

- name: Install packages from extra sources
  block:
    - name: Import key
      ansible.builtin.apt_key:
        url: "{{ item.key }}"
        state: present
      loop: "{{ extra_sources }}"

    - name: Install extra repos
      ansible.builtin.apt_repository:
        repo: "{{ item.deb_line }}"
        filename: "{{ item.filename }}"
        state: present
      loop: "{{ extra_sources }}"

    - name: Install extra packages
      ansible.builtin.apt:
        name: "{{ item.pkg }}"
        state: present
      loop: "{{ extra_sources }}"
