---
- name: Initialize variables
  ansible.builtin.include_vars: vars/graphical.yml

- name: Install GNOME packages
  ansible.builtin.apt:
    name: "{{ gnome_pkgs }}"
    state: present
  when: desktop == "gnome"

- name: Install Nautilus image helpers
  ansible.builtin.apt:
    name: "{{ image_pkgs }}"
    state: present
  when: desktop == "gnome"

- name: Install extra repos
  ansible.builtin.deb822_repository:
    name: "{{ item.sources_name }}"
    types: deb
    uris: "{{ item.uri }}"
    suites: "{{ item.suites }}"
    components: "{{ item.components }}"
    signed_by: "{{ item.gpg }}"
  loop: "{{ x64_extra_repos if ansible_architecture == 'x86_64' else aarch64_extra_repos }}"
