---
- name: Ubuntu setup
  hosts: ubuntu
  become: true
  tasks:
    - name: Install base packages
      ansible.builtin.import_tasks: base.yml

    - name: Install graphical packages
      ansible.builtin.import_tasks: graphical.yml
      when: graphical

    - name: Install Iosevka fonts
      ansible.builtin.import_tasks: iosevka-font.yml
      when: graphical

    - name: Install kuberntes tools
      ansible.builtin.import_tasks: kubernetes-tools.yml
      when: kubernetes_tools
