---
- hosts: ubuntu
  become: yes
  tasks:
    - name: Install base packages
      import_tasks: base.yml

    - name: Install graphical packages
      import_tasks: graphical.yml
      when: graphical == true
