---
graphical_pkgs:
  - meld
  - foot
  - vlc

gnome_pkgs:
  #  - gnome-photos
  - gnome-applets
  - gnome-authenticator
  - gnome-calculator
  - gnome-calendar
  - gnome-clocks
  - gnome-console
  - gnome-contacts
  - gnome-dictionary
  - gnome-firmware
  - gnome-keyring
  - gnome-maps
  - gnome-software
  - gnome-software-plugin-snap
  - gnome-tweaks
  - gnome-text-editor
  - gnome-remote-desktop
  - gnome-weather
  - gnome-shell-extension-manager

gnome_shell_extensioons:
  - compiz-windows-effect@hermes83.github.com
  - Vitals@CoreCoding.com
  - user-theme@gnome-shell-extensions.gcampax.github.com
  - lan-ip-address@mrhuber.com
  - bluetooth-quick-connect@bjarosze.gmail.com
  - uptime-indicator@gniourfgniourf.gmail.com
  - wireless-hid@chlumskyvaclav.gmail.com
  - ding@rastersoft.com
  - gravatar@dsheeler.net

# Nautilus image support
image_pkgs:
  - heif-gdk-pixbuf
  - webp-pixbuf-loader
  - libavif-gdk-pixbuf
  - gtk2-engines-pixbuf
  - libextractor-plugin-thumbnailgtk

x64_extra_repos:
  - name: Chrome
    sources_name: google-chrome
    # uris: https://dl.google.com/linux/chrome/rpm/stable/x86_64
    gpg: "{{ lookup('ansible.builtin.url', 'https://dl.google.com/linux/linux_signing_key.pub', split_lines=False) }}"
    uri: https://dl.google.com/linux/chrome/deb/
    suites: stable
    components:
      - main
  - name: Microsoft
    sources_name: microsoft
    gpg: "{{ lookup('ansible.builtin.url', 'https://packages.microsoft.com/keys/microsoft.asc', split_lines=False) }}"
    uri: https://packages.microsoft.com/repos/code
    suites: stable
    components:
      - main

aarch64_extra_repos:
  - sources_name: microsoft
    gpg: "{{ lookup('ansible.builtin.url', 'https://packages.microsoft.com/keys/microsoft.asc', split_lines=False) }}"
    uri: https://packages.microsoft.com/repos/code
    suites: stable
    components:
      - main
