---
- name: Initialize install set
  ansible.builtin.include_vars: vars/base.yml

- name: Install RPM Fusion repos
  ansible.builtin.dnf:
    name: "{{ rpmfusion_repos }}"
    state: present
    disable_gpg_check: true

- name: Install base packages
  ansible.builtin.dnf:
    name: "{{ base_pkgs }}"
    state: present
