---
- name: Initialize variables
  ansible.builtin.include_vars: vars/graphical.yml

- name: Install packages from extra repos
  block:
    - name: Install repos
      ansible.builtin.yum_repository:
        name: "{{ item.filename }}"
        description: "{{ item.description }}"
        baseurl: "{{ item.baseurl }}"
        gpgkey: "{{ item.key }}"
        state: present
        enabled: true
      loop: "{{ extra_repos }}"

- name: Install GNOME packages
  ansible.builtin.dnf:
    name: "{{ gnome_pkgs }}"
    state: present
  when: desktop == "gnome"

- name: Install graphical packages
  ansible.builtin.dnf:
    name: "{{ graphical_pkgs }}"
    state: present

- name: Install free world packages
  ansible.builtin.dnf:
    name: "{{ freeworld_pkgs }}"
    state: present

- name: Install additonal image support
  ansible.builtin.dnf:
    name: "{{ image_pkgs }}"
    state: present
  when: desktop == "gnome"

- name: Install fonts
  block:
    - name: Install Iosevka Copr
      community.general.copr:
        name: peterwu/iosevka
        state: enabled

    - name: Install Iosevka fonts
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - iosevka-slab-fonts
        - iosevka-curly-slab-fonts
