---
- name: Fedore setup
  hosts: fedora
  become: true
  tasks:
    - name: Install base packages
      ansible.builtin.import_tasks: base.yml

    - name: Install graphical packages
      ansible.builtin.import_tasks: graphical.yml
      when: graphical
