---
- name: Avahi tasks
  hosts: linux
  become: true

  tasks:
    - name: Install avahi via dnf
      vars:
        avahi_dnf_list:
          - avahi
          - avahi-tools
          - avahi-dnsconfd
      ansible.builtin.dnf:
        name: "{{ avahi_dnf_list }}"
        state: present
      when: ansible_os_family == 'Redhat'

    - name: Install avahi via ansible.builtin.apt
      vars:
        avahi_apt_list:
          - avahi-daemon
          - avahi-dnsconfd
          - avahi-utils
      ansible.builtin.apt:
        name: "{{ avahi_apt_list }}"
        state: present
      when: ansible_os_family == 'Debian'

    - name: Publish SSH and SFTP services for Avahi
      ansible.builtin.template:
        src: avahi_ssh_sftp.service.j2
        dest: /etc/avahi/services/ssh_sftp.service
        mode: u=rw,go=r

    - name: Enable avahi to start
      ansible.builtin.systemd:
        name: avahi-daemon
        state: started
        enabled: true
        masked: false
        daemon_reload: true
