---
- hosts: linux
  become: yes
  vars:
    machine:
      aliases_path: /etc/profile.d/aliases.sh

  tasks:
    - name: Use a safer umask default for Debian distros
      lineinfile:
        path: "{{ item }}"
        regexp: "^session optional\\s+pam_umask.so$"
        line: "session optional pam_umask.so umask={{ umask }}"
      loop:
        - /etc/pam.d/common-session
        - /etc/pam.d/common-session-noninteractive
      when: ansible_os_family == 'Debian'

    - name: Use a safer umask default for RedHat distros
      lineinfile:
        path: "{{ item }}"
        regexp: "^session\\s+optional\\s+pam_umask.so"
        line: "session optional pam_umask.so umask={{ umask }} silent"
      loop:
        - /etc/pam.d/postlogin
      when: ansible_os_family == 'RedHat'


    - name: Deploy common aliases
      template:
        src: aliases.sh.j2
        dest: "{{ machine.aliases_path }}"

    - name: Default shell and skel files for new users
      block:
        - name: Enable skeleton files for all new users
          lineinfile:
            path: /etc/default/useradd
            regexp: ^[# ]*SKEL=(.*)$
            line: SKEL=\g<1>
            state: present
            backrefs: yes

        - name: Load tmux file configuration
          include_vars: vars/tmux-config.yml

        - name: Deploy tmux configuration for all new users
          get_url:
            url: "{{ item.url }}"
            dest: "/etc/skel/{{ item.filename }}"
          loop: "{{ tmux.files }}"

        - name: Enable bash completion for all new users
          template:
            src: global-.bashrc.j2
            dest: /etc/skel/.bashrc


    - name: Admin group for sudo access
      block:
        - name: Create admin group
          group:
            name: "{{ sudo_group | mandatory }}"
            state: present

        - name: Deploy sudoers file
          template:
            src: admin.sudo.j2
            dest: "/etc/sudoers.d/{{ sudo_group | mandatory }}"
            owner: root
            group: root
            mode: "u=rw,g=,o="

