---
- name: Import machine tasks
  import_playbook: machine.yml

- name: Import Avahi tasks
  import_playbook: avahi.yml
  when: (avahi is defined) and (avahi == True)

- name: Import virtualization tasks
  import_playbook: virt.yml
  when: (virtualization is defined) and (virtualization == True)

- name: Common setups for all linux systems
  hosts: linux
  become: true
  tasks:
    - name: Add current user to the admin
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: "{{ sudo_group | mandatory }}"
        append: true

    - name: Install and configure user specific tools
      become: false
      ansible.builtin.import_tasks: user.yml

    - name: Install and configure graphical tools
      ansible.builtin.import_tasks: graphical.yml
      when: graphical
