---
- import_playbook: machine.yml

- import_playbook: avahi.yml
  when: (avahi is defined) and (avahi == True)

- import_playbook: virt.yml
  when: (virtualization is defined) and (virtualization == True)

- hosts: linux
  become: yes
  tasks:
    - name: Add current user to the admin
      user:
        name: "{{ ansible_facts.env.SUDO_USER }}"
        groups: "{{ sudo_group | mandatory }}"
        append: yes

    - name: Install and configure user specific tools
      become: no
      import_tasks: user.yml

    - name: Install and configure graphical tools
      import_tasks: graphical.yml
      when: graphical == true
