---
- name: Load tmux configuration
  ansible.builtin.include_vars: vars/tmux-config.yml

- name: Deploy tmux files
  vars:
    templates:
      - tmux.conf
      - tmux.local.conf
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "~/.{{ item }}"
    mode: u=rw
  loop: "{{ templates }}"
