---
- name: Import variables
  ansible.builtin.include_vars: vars/user-config.yml

- name: Configure tmux
  ansible.builtin.include_tasks: tmux.yml

- name: Configure vim
  ansible.builtin.include_tasks: vim.yml

- name: Configure zsh
  ansible.builtin.include_tasks: zsh.yml

- name: Change current user's shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_facts.env.SUDO_USER }}"
    shell: /usr/bin/zsh

- name: Create .local/bin directory
  become: false
  ansible.builtin.file:
    path: "~/.local/bin"
    state: directory
    mode: "u=rwx,go="

- name: Setup common ssh options
  become: false
  block:
    - name: Create .ssh directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "u=rwx,go="
      loop:
        - "~/.ssh"
        - "~/.ssh/multiplex"

    - name: Check if ~/.ssh/config exists
      ansible.builtin.stat:
        path: "~/.ssh/config"
      register: ssh_config

    - name: Create ~/.ssh/config
      ansible.builtin.file:
        path: "~/.ssh/config"
        state: touch
        mode: "u=rw,go="
      when: not ssh_config.stat.exists

    - name: Add common ssh options
      ansible.builtin.blockinfile:
        path: "~/.ssh/config"
        block: |
          Host *
            ForwardX11              no
            ForwardAgent            yes
            Compression             yes
            StrictHostKeyChecking   no
            ControlMaster           auto
            ControlPath             ~/.ssh/multiplex/%r@%h:%p
            ControlPersist          1
