---
- name: Import variables
  include_vars: vars/user-config.yml

- name: Configure tmux
  include_tasks: tmux.yml

- name: Configure vim
  include_tasks: vim.yml

- name: Configure zsh
  include_tasks: zsh.yml
