---

- name: Load vim configuration
  ansible.builtin.include_vars: vars/vim-config.yml

- name: Configure vim
  become: false
  block:
    - name: Create directories needed for vim
      ansible.builtin.file:
        name: "{{ item }}"
        state: directory
        mode: u=rwx
      loop:
        - "~/.vim"
        - "~/.vim/autoload"
        - "~/.vim/bundle"

    - name: Deploy .vimrc
      ansible.builtin.template:
        src: ".vimrc.j2"
        dest: "~/.vimrc"
        mode: u=rw

    - name: Deploy pathogen
      ansible.builtin.get_url:
        url: "{{ vim.pathogen_url }}"
        dest: "~/.vim/autoload/pathogen.vim"
        mode: u=rw

    - name: Deploy bundles
      ansible.builtin.git:
        repo: "{{ item.url }}"
        dest: "~/.vim/bundle/{{ item.name }}"
        version: "{{ item.branch }}"
      loop: "{{ vim.bundles }}"

