---
- name: Setup (virtualization
  hosts: linux
  gather_facts: true
  become: true

  vars:
    podman_rpms:
      - podman
      - podman-docker
      - podman-compose
      - podman-tui
    podman_debs:
      - podman
      - podman-compose
      - podman-docker
      - podman-toolbox

    virt_group: libvirt

  tasks:
    - name: Install RPM packages for podman
      ansible.builtin.dnf:
        name: "{{ podman_rpms }}"
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install Deb package for podman
      ansible.builtin.apt:
        name: "{{ podman_debs }}"
        state: present
      when: ansible_os_family == 'Debian'

    - name: Enable libvirt group
      block:
        - name: Create libvirt group
          ansible.builtin.group:
            name: "{{ virt_group }}"
            state: present
            system: true

        - name: Add user to the group
          ansible.builtin.user:
            name: "{{ ansible_env.USER }}"
            groups: "{{ virt_group }}"
            append: true
