---
- hosts: linux
  become: yes

  vars:
    podman_rpms:
      - podman
      - podman-docker
      - podman-compose
      - podman-plugins
      - podman-tui
      # - libvirt-daemon-kvm

    podman_debs:
      - podman
      - podman-compose
      - podman-docker
      - podman-toolbox

    virt_group: libvirt

  tasks:
    - name: Install RPM packages for podman
      dnf:
        name: "{{ podman_rpms }}"
        state: present
      when: ansible_os_family == 'Redhat'

    - name: Install Deb package for podman
      apt:
        name: "{{ podman_debs }}"
        state: present
      when: ansible_os_family == 'Debian'

    - name: Enable libvirt group
      block:
        - name: Create libvirt group
          group:
            name: "{{ virt_group }}"
            state: present
            system: yes

        - name: Add user to the group
          user:
            name: "{{ ansible_user }}"
            groups: "{{ virt_group }}"
            append: yes
