---
base_pkgs:
  - curl
  - fzf
  - git
  - htop
  - ranger
  - tig
  - tmux
  - zsh
  - powertop
  - vim-enhanced
  - bluez-tools
  # - rust-exa  # Enable later

#  - tmuxinator

rpmfusion_repos:
  - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
  - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
